package rest.spr.api.domain.curso;
/**CREATED BY Edgar M Gómez P
 * Backend Developer*/
public enum Nombre {
    ANGULAR,
    JAVASCRIPT_VALIDACION,
    JAVASCRIPT_CONSUMIENDO_API,
    INTELIGENCIA_ARTIFICIAL,
    DATABASE,
    INNOVACION_Y_GESTION,
    DESARROLLO_PERSONAL,
    BUSINESS_AGILITY,
    PROGRAMACION,
    ESPECIALIZACION_BACKEND,
    EMPRENDIMIENTO,
    JAVA_ORIENTADO_A_OBJETOS,
    JAVA_Y_SPRING_BOOT,
    SIN_REGISTRO
}
